# Generated by Django 4.1 on 2022-10-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labSoft3", "0002_factura_mesa_producto_reserva"),
    ]

    operations = [
        migrations.CreateModel(
            name="provedores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_provedor", models.CharField(max_length=200)),
                ("nombre_producto", models.CharField(max_length=200)),
                ("cantidad", models.IntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_producto", models.CharField(max_length=200)),
                ("cantidad", models.IntegerField()),
            ],
        ),
    ]
